# Generated by Django 2.1.2 on 2019-02-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
