# Generated by Django 2.1.2 on 2019-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190212_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
